### ISSUE TITLE
I got "s6-overlay-suexec: fatal: can only run as pid 1" issue

### ISSUE THREAD

**Issue by Siteac** [hotio/radarr#20]
I got a "s6-overlay-suexec: fatal: can only run as pid 1" error when starting container. Tried on current release (4.3.2.6857), nighlty (4.4.3.7000).

Any idea ? 
I'm using cloudbox (https://github.com/Cloudbox/Cloudbox) and update to last images to get this problem.

Thank you for you help.

**Comment by mrhotio** [comment]
Use discord for support
