### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by hskrtich** [hotio/radarr#21]
Hi, can a health check for sonarr be added to the dockerfile?

See https://radarr.video/docs/api/#/Ping/get_ping

https://docs.docker.com/engine/reference/builder/#healthcheck

```
HEALTHCHECK --start-period=30s --timeout=3s \
  curl -sSf http://127.0.0.1:7878/ping || exit 1
```

**Comment by mrhotio** [comment]
You can do it yourself
