### ISSUE TITLE
support for arm v7?

### ISSUE THREAD

**Issue by manugarri** [hotio/radarr#23]
Im trying to install radar on a My Cloud Ex Ultra 2 NAS via portainer. however I cant seem to find a docker image that supports the `linux/arm/v7` architecture. 

Is that something that could be added to your repository? or maybe you could give me pointers on how I could to to build one myself? 

Thanks in advance!

**Comment by mrhotio** [comment]
Arm v7 support has been removed, so it won’t be coming back.
